import { Injectable } from '@angular/core';
import { WorkshopEvent } from 'shared-kernel';

@Injectable({
  providedIn: 'root',
})
export class EventsCatalogService {
  private readonly events: WorkshopEvent[] = [
    {
      id: 'aurora-ai-agents',
      title: 'IA Generativa Aplicada & Agentes Autónomos',
      subtitle: 'Construye sistemas multi-agente con LLMs, RAG híbrido y orquestación para producción.',
      category: 'ai',
      categoryLabel: 'Inteligencia Artificial',
      level: 'Avanzado',
      modality: 'Virtual',
      location: 'Live Streaming Ultra HD + Lab Virtual',
      duration: '16 Horas • 4 Sesiones Intensivas',
      startDate: '24 Octubre 2026',
      badge: 'Bestseller ★ 4.98',
      price: 380,
      originalPrice: 480,
      spotsTotal: 30,
      spotsRemaining: 4,
      accentGradient: 'linear-gradient(135deg, #6366f1 0%, #a855f7 100%)',
      instructor: {
        name: 'Dra. Valeria Montes',
        role: 'Principal AI Architect & Research Fellow',
        company: 'Ex-DeepMind / AI Frontier Labs',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
        bio: 'Pionera en arquitectura de agentes y fine-tuning de modelos fundacionales con más de 12 patentes en NLP.',
        badge: 'Speaker Internacional',
      },
      description: 'Sumérgete en la vanguardia de la IA: desde patrones de razonamiento (Chain-of-Thought, ReAct) hasta pipelines de evaluación continua y despliegue tolerante a fallas con Vector Databases.',
      topics: [
        'Arquitectura de Agentes: Planificación, Memoria y Herramientas externas',
        'RAG Avanzado: GraphRAG, reranking contextual y embeddings híbridos',
        'Fine-tuning eficiente (LoRA/QLoRA) vs prompting estructurado',
        'Observabilidad, costos y seguridad frente a Prompt Injections',
      ],
      includes: [
        'Certificado Verificado con Hash en Blockchain',
        'Acceso de por vida a grabaciones 4K y notebooks',
        'Plantillas de código de grado enterprise listas para producción',
        'Comunidad privada de Discord con soporte de la instructora',
      ],
      scheduleDates: [
        { id: 'ai-s1', date: '24 Oct 2026', dayName: 'Sábado', time: '09:00 - 13:00 (UTC-5)', period: 'Mañana', availableSeats: 2 },
        { id: 'ai-s2', date: '31 Oct 2026', dayName: 'Sábado', time: '09:00 - 13:00 (UTC-5)', period: 'Mañana', availableSeats: 2 },
        { id: 'ai-s3', date: '07 Nov 2026', dayName: 'Sábado', time: '14:00 - 18:00 (UTC-5)', period: 'Tarde', availableSeats: 0 },
      ],
    },
    {
      id: 'aurora-micro-frontends',
      title: 'Arquitectura Micro Frontends & Modular Enterprise',
      subtitle: 'Diseño de sistemas distribuidos a gran escala con Angular, Native Federation y Monorepos.',
      category: 'architecture',
      categoryLabel: 'Arquitectura Web',
      level: 'Avanzado',
      modality: 'Híbrido',
      location: 'Hub Central Medellín & Live Stream Global',
      duration: '14 Horas • 3 Sesiones Teórico-Prácticas',
      startDate: '12 Noviembre 2026',
      badge: 'Nivel Ejecutivo',
      price: 340,
      originalPrice: 420,
      spotsTotal: 25,
      spotsRemaining: 3,
      accentGradient: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
      instructor: {
        name: 'Mateo Cárdenas',
        role: 'VP of Engineering & Staff Architect',
        company: 'Unicorn FinTech Labs',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
        bio: 'Especialista en escalabilidad frontend para empresas con más de 200 ingenieros sincronizados.',
        badge: 'Google Developer Expert',
      },
      description: 'Aprende a desacoplar monstruos monolíticos en micro frontends independientes con despliegues autónomos, contratos de estado compartidos y rendimiento de primer nivel.',
      topics: [
        'Domain-Driven Design (DDD) aplicado al Frontend',
        'Native Federation sin Webpack: Configuración y Dynamic Host Loading',
        'Manejo de estado federado, Signals y buses de eventos reactivos',
        'Estrategias CI/CD para despliegues independientes con cero downtime',
      ],
      includes: [
        'Certificación Oficial AURORA Architect Tier',
        'Monorepo Enterprise base con configuraciones listas',
        'Revisión 1-a-1 de tu arquitectura actual de empresa',
        'Acceso al canal VIP de graduados de arquitectura',
      ],
      scheduleDates: [
        { id: 'mfe-s1', date: '12 Nov 2026', dayName: 'Jueves', time: '18:00 - 22:00 (UTC-5)', period: 'Noche', availableSeats: 1 },
        { id: 'mfe-s2', date: '14 Nov 2026', dayName: 'Sábado', time: '10:00 - 15:00 (UTC-5)', period: 'Mañana', availableSeats: 2 },
      ],
    },
    {
      id: 'aurora-design-systems',
      title: 'Design Systems & UI Engineering de Clase Mundial',
      subtitle: 'De Figma a Componentes de Código Resilientes con Tokens, Accesibilidad y Micro-animaciones.',
      category: 'ux',
      categoryLabel: 'Diseño & Producto',
      level: 'Intermedio',
      modality: 'Virtual',
      location: 'Figma Live Workspace + CodeSandbox',
      duration: '12 Horas • 3 Sesiones',
      startDate: '20 Noviembre 2026',
      badge: 'Tendencia 2026',
      price: 290,
      originalPrice: 360,
      spotsTotal: 35,
      spotsRemaining: 8,
      accentGradient: 'linear-gradient(135deg, #f43f5e 0%, #fb923c 100%)',
      instructor: {
        name: 'Camila Villalobos',
        role: 'Head of Design Systems & UX Research',
        company: 'Stripe Ecosystem Partner',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
        bio: 'Diseñadora de interacción galardonada en los Awwwards y conferencista internacional de Design Ops.',
        badge: 'Design Leader',
      },
      description: 'El puente definitivo entre diseño y desarrollo: cómo construir bibliotecas de componentes ultra-accesibles (WCAG AAA), con tokens multiplataforma y documentación viva.',
      topics: [
        'Arquitectura de Design Tokens con Style Dictionary y Figma Variables',
        'Patrones de componentes complejos, accesibilidad semántica y ARIA',
        'Microinteracciones con CSS moderno y físicas de animación fluidas',
        'Gobierno y versionado semántico del Design System',
      ],
      includes: [
        'Kit de UI en Figma con más de 200 componentes premium',
        'Repositorio de código listo con Storybook y pruebas de regresión visual',
        'Certificado de Especialista en Design Systems',
      ],
      scheduleDates: [
        { id: 'ds-s1', date: '20 Nov 2026', dayName: 'Viernes', time: '17:00 - 21:00 (UTC-5)', period: 'Tarde', availableSeats: 5 },
        { id: 'ds-s2', date: '21 Nov 2026', dayName: 'Sábado', time: '09:00 - 13:00 (UTC-5)', period: 'Mañana', availableSeats: 3 },
      ],
    },
    {
      id: 'aurora-eng-leadership',
      title: 'Executive Tech Leadership & High Performance Teams',
      subtitle: 'Herramientas de decisión estratégica para Engineering Managers, Tech Leads y futuros VP.',
      category: 'leadership',
      categoryLabel: 'Liderazgo & Estrategia',
      level: 'Avanzado',
      modality: 'Presencial',
      location: 'Grand Ballroom Innovación, Bogotá (Cupos VIP Exclusivos)',
      duration: '10 Horas • 1 Jornada Completa + Cóctel de Networking',
      startDate: '05 Diciembre 2026',
      badge: 'Exclusivo Presencial',
      price: 520,
      originalPrice: 650,
      spotsTotal: 20,
      spotsRemaining: 2,
      accentGradient: 'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)',
      instructor: {
        name: 'Sebastián Morales',
        role: 'Former CTO & Board Advisor',
        company: 'ScaleUp Ventures & Seedstars',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
        bio: 'Ha liderado el escalamiento de 4 compañías desde Serie A hasta rondas de más de $80M.',
        badge: 'Executive Mentor',
      },
      description: 'Domina el arte de la gestión técnica: desde cómo influir en juntas directivas y gestionar deudas técnicas estratégicas, hasta cultura de ingeniería y retención de talento senior.',
      topics: [
        'Traducción de métricas técnicas a valor financiero para el Board',
        'Modelos de compensación, planes de carrera y evaluación de desempeño',
        'Gestión de crisis arquitecturales e incidentes críticos',
        'Estrategias de adopción de IA corporativa sin riesgos de cumplimiento',
      ],
      includes: [
        'Pase VIP completo con almuerzo ejecutivo gourmet y cena de networking',
        'Plantillas confidenciales de OKRs, matrices de habilidades y presupuestos',
        'Sesión privada de mentoría 1-a-1 de 45 minutos post-taller',
      ],
      scheduleDates: [
        { id: 'lead-s1', date: '05 Dic 2026', dayName: 'Sábado', time: '08:30 - 19:00 (Presencial)', period: 'Mañana', availableSeats: 2 },
      ],
    },
    {
      id: 'aurora-cloud-finops',
      title: 'Cloud FinOps & Kubernetes Production Mastery',
      subtitle: 'Optimiza costos en AWS/GCP hasta un 45% mientras escalas clusters con resiliencia total.',
      category: 'cloud',
      categoryLabel: 'Cloud & DevOps',
      level: 'Intermedio',
      modality: 'Virtual',
      location: 'Laboratorio Cloud Hands-On',
      duration: '12 Horas • 3 Sesiones',
      startDate: '11 Diciembre 2026',
      badge: 'Retorno de Inversión Inmediato',
      price: 310,
      originalPrice: 390,
      spotsTotal: 30,
      spotsRemaining: 6,
      accentGradient: 'linear-gradient(135deg, #10b981 0%, #0284c7 100%)',
      instructor: {
        name: 'Andrea Restrepo',
        role: 'Principal Cloud Architect',
        company: 'Global Cloud Solutions',
        avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=160&auto=format&fit=crop&q=80',
        bio: 'Consultora de infraestructura que ha recortado más de $2.5M en facturas cloud para empresas internacionales.',
        badge: 'AWS Ambassador',
      },
      description: 'Aprende a transformar la factura cloud en una ventaja competitiva: asignación granular de costos, autoscaling predictivo, spot instances seguras y observabilidad con OpenTelemetry.',
      topics: [
        'Estrategia de Tagging y atribución de costos por microservicio',
        'Kubernetes Resource Requests, Limits y Rightsizing automatizado',
        'Arquitectura Spot & Graviton/ARM para cargas de trabajo críticas',
        'Dashboards ejecutivos de FinOps y presupuestos con alertas en tiempo real',
      ],
      includes: [
        'Créditos para laboratorio cloud durante el taller',
        'Scripts automatizados de auditoría de costos',
        'Certificado de Finalización AURORA Cloud FinOps',
      ],
      scheduleDates: [
        { id: 'fin-s1', date: '11 Dic 2026', dayName: 'Viernes', time: '17:00 - 21:00 (UTC-5)', period: 'Tarde', availableSeats: 4 },
        { id: 'fin-s2', date: '12 Dic 2026', dayName: 'Sábado', time: '09:00 - 13:00 (UTC-5)', period: 'Mañana', availableSeats: 2 },
      ],
    },
  ];

  getAllEvents(): WorkshopEvent[] {
    return [...this.events];
  }

  getEventById(id: string): WorkshopEvent | undefined {
    return this.events.find((e) => e.id === id);
  }
}
